MIN_BET = 1
MAX_BET: int | None = None

EXP_WIN_RATE = 0.2
EXP_LOSE_RATE = 0.1
EXP_DRAW_RATE = 0.05

BLACKJACK_PAYOUT_MULTIPLIER = 3
NORMAL_WIN_PAYOUT_MULTIPLIER = 2
DRAW_PAYOUT_MULTIPLIER = 1

DEALER_STAND_SCORE = 17
SAVED_DECK_SIZE = 13
