LEADERBOARD_LIMIT = 10

CATEGORY_COINS = "coins"
CATEGORY_LEVEL = "level"
CATEGORY_WINS = "wins"
CATEGORY_PROFIT = "profit"
CATEGORY_BET = "bet"
CATEGORY_ACHIEVEMENTS = "achievements"

CATEGORIES = (CATEGORY_COINS, CATEGORY_LEVEL, CATEGORY_WINS, CATEGORY_PROFIT, CATEGORY_BET, CATEGORY_ACHIEVEMENTS)
